$(document).ready ->
  $(".menu .tab a").corner("tr 17px").corner "tl 17px"
  $(".menu .tab a:hover").corner("tr 17px").corner "tl 17px"
  $("#about .border").corner "10px"
  $("#apartments .border").corner "10px"
  $("#apartments .button a").corner "10px"
  $("#availability .button a").corner "10px"
  $("#apartment .border").corner "10px"
  $("#flash .alert").corner "0.5em"
  $("#flash .notice").corner "0.5em"