require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortraitsController do

  # This should return the minimal set of attributes required to create a valid
  # Portrait. As you add validations to Portrait, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all portraits as @portraits" do
      portrait = Portrait.create! valid_attributes
      get :index
      assigns(:portraits).should eq([portrait])
    end
  end

  describe "GET show" do
    it "assigns the requested portrait as @portrait" do
      portrait = Portrait.create! valid_attributes
      get :show, :id => portrait.id.to_s
      assigns(:portrait).should eq(portrait)
    end
  end

  describe "GET new" do
    it "assigns a new portrait as @portrait" do
      get :new
      assigns(:portrait).should be_a_new(Portrait)
    end
  end

  describe "GET edit" do
    it "assigns the requested portrait as @portrait" do
      portrait = Portrait.create! valid_attributes
      get :edit, :id => portrait.id.to_s
      assigns(:portrait).should eq(portrait)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Portrait" do
        expect {
          post :create, :portrait => valid_attributes
        }.to change(Portrait, :count).by(1)
      end

      it "assigns a newly created portrait as @portrait" do
        post :create, :portrait => valid_attributes
        assigns(:portrait).should be_a(Portrait)
        assigns(:portrait).should be_persisted
      end

      it "redirects to the created portrait" do
        post :create, :portrait => valid_attributes
        response.should redirect_to(Portrait.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portrait as @portrait" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portrait.any_instance.stub(:save).and_return(false)
        post :create, :portrait => {}
        assigns(:portrait).should be_a_new(Portrait)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portrait.any_instance.stub(:save).and_return(false)
        post :create, :portrait => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portrait" do
        portrait = Portrait.create! valid_attributes
        # Assuming there are no other portraits in the database, this
        # specifies that the Portrait created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Portrait.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => portrait.id, :portrait => {'these' => 'params'}
      end

      it "assigns the requested portrait as @portrait" do
        portrait = Portrait.create! valid_attributes
        put :update, :id => portrait.id, :portrait => valid_attributes
        assigns(:portrait).should eq(portrait)
      end

      it "redirects to the portrait" do
        portrait = Portrait.create! valid_attributes
        put :update, :id => portrait.id, :portrait => valid_attributes
        response.should redirect_to(portrait)
      end
    end

    describe "with invalid params" do
      it "assigns the portrait as @portrait" do
        portrait = Portrait.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portrait.any_instance.stub(:save).and_return(false)
        put :update, :id => portrait.id.to_s, :portrait => {}
        assigns(:portrait).should eq(portrait)
      end

      it "re-renders the 'edit' template" do
        portrait = Portrait.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portrait.any_instance.stub(:save).and_return(false)
        put :update, :id => portrait.id.to_s, :portrait => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portrait" do
      portrait = Portrait.create! valid_attributes
      expect {
        delete :destroy, :id => portrait.id.to_s
      }.to change(Portrait, :count).by(-1)
    end

    it "redirects to the portraits list" do
      portrait = Portrait.create! valid_attributes
      delete :destroy, :id => portrait.id.to_s
      response.should redirect_to(portraits_url)
    end
  end

end
